export interface Page {
  number: number;
  content: string;
  _id: string;
  __v: number;
}

const pages: Array<Page> = [
  {
    _id: '5e03ef45c00a2307507d47af',
    number: 5,
    content:
      'the pelvic floor\nlayers pelvic floor consists of the soft tissues filling the outlet of the bony pelvis\n1 - pelvic peritoneum\nlateral to uterus it forms broad ligament\nanteriorly it reflected at internal os and forming utero vesical pouch\nposterior it reflected at the upper vagina forming douglas pouch\n2 - pelvic cellular tissue "endo-pelvic fascia"\nfill between the pelvic organs & the 2 layers of broad ligament\nit surrounds cervix & upper vagina is called parametrium\nthe cervical ligament are condensations of this fascia \ni.e cardinal pubocervical uterosacral ligament.\nit\'s extraperitoneal & is contiuous with:\nperi-renal fascia \nfascia of thigh through obturator foramen\nfascia of buttocks through sarcosciatic foramen\n\n3 - Levator ani\nparts:\na. pubo coccygeus\norigin: back of public bone\ninsertion: medial apex of perineal body\nlateral coccyx & rectum\n- hiatuses are present in midline between the 2 levators\n* the rectal hiatus\n* the urgogenital hiatus for urethra & vagina to pass.\n\nb. ileo-coccygeus\norigin: line on obturator internus\ninsertion: coccyx & anococcygeal\n\nc. ischio-coccygeus\norigin: ischial spine\ninsertion: inserted in the coccyx\n',
    __v: 0,
  },
  {
    _id: '5e04261fc00a2307507d47b0',
    number: 6,
    content:
      "Function of levator ani:\n- Support of pelvic organs\n- Sphincter action for rectum and vagina\n- Internal rotation during second stage of labor\n\nNerve Suuply:\n- Pedundal nerve s 2,3,4\n- Direct branches from third & fourth sacral roots\n\n4 - Perineal muscles\n- Bulbocavernosus\n- Ischio cavernosus\n- Transverse perineal\n- External anal sphincter\n\n5 - perineal skin & fascia\nthis is the outer layer consists of perineal skin & Colle's fascia\n\nApplied anatomy:\n- Weakness of cervical ligaments or the levator ani predispose to\nGenital prolapse & stress incontinence\nThis due to:\n1 - Obstetric trauma\n2 - Postmenopausal atrophy\n3 - Congenital\n- Parametric abscess points through the sciatic or obturator foramina\n- Lax or rigid pelvic floor interferes with internal rotation during labor",
    __v: 0,
  },
  {
    _id: '5e0429f2c00a2307507d47b1',
    number: 7,
    content:
      'The external genitalia "Vulva"\n\n1- The mons pubis "Mons uneris"\n- An elevation of fat covered by skin infront of the symphysis pubis\n- In females the public hair has straight upper border\n\n2- The Labia Majora\n- These are 2 Skin folds extend from mons pubis to perineum\n- Contains sebaceous & sweat glands & lined by hair on the outer side\n- Homologous to scrotum in males\n- Anterior it contains insertion of round ligaments\n\n3- The Labia Minora "nymphae"\n- 2 skin folds lying medial to labia majora\n- Contain sebaceous glands & but no hair follicles\n- Homologous to penile urethra\n- Anterior each labium divides into prepuce & frenulum of clitoris.\n- Posterior junction of labia minora forms fourchete\n\n4- Vestibule\n- Area between 2 labia minora it contains external urethral meatus \n& the opening of vagina \n& Bartholin duct\n\n5- Skene\'s tubules\n- 2 blind tubules opening in the floor of urethra few millimeters from external urethral meatus\n- Homologous of prostate\n\n6- Hymen\n- Membrane lies at the vagina introitus\n- Covered both sides with stratified squamous epithelium\n- Contains opening to allow escape of \nmenstrual blood\n& Vaginal discharge\nthe opening takes one of the following shapes\nAnnular\nSeptate\nCrescentic\nCribiform\nAbscent or imperforate\n- Torn after first sexual intercourse\n- Remnants after 1st labor called carunculae myritiformes\n- The fossa navicularis is a depression between the fourchette & hymen in virgins\n\n7-  Bartholin\'s glands "Greater vestibular glands"\n- Bilateral compound racemose glands\n- Pea sized & not palpable unless disease\n- In posterior part of labia majora\nIt has duct 2cm thats opens between hymen \n- The gland lined by columnar epithelium\n- The duct lined by transitional epithelium\n- It secrete alkaline mucus during coitus act as a lubricant\n- It is homologous to COWPER\'S bulbourethral glands in male \n\n8- Clitoris\n- The clitoris consists of erectile etremely sensitive cavernouse tissue\n- Forms of a glands and 2 crura\n- It is attached to the front of pubic bonde by a suspensory ligament\n',
    __v: 0,
  },
  {
    _id: '5e04f7c0cdb09e0b324430f2',
    number: 8,
    content:
      'Development\nThe vulva develops from the urgogenital sinus\n- Clitoris from genital tubercle\n- Labia majora from labioscrotal swelling\n- Labia minora from genital folds\nCongenital anomalies\n- Clitoridal cyst\n- Congenital hypertrophy of clitoris\n- Congenital dermoid cyst\n\nBlood supply\narteries\n- Internal pudendal artery branch from iliac\n- External pudendal artery branch from femoral\nviens\n- Accompany the corresponding arteries\n- Veins draining the clitoris join the vesical & vaginal plexuses\n\nlymphatic drainage\n- vulva drains to superficial inguinal lymph nodes. From these nodes pass to\ndeep inguinal then deep femoral nodes\nincluding highest lymph nodes i.e cloquet\n- From above nodes lymphatics pass to external & common iliac lymph nodes\nthen para aortic lymph nodes\n\nSurgical anatomy\nIn radical vulvectomy done for vulva cancer, \nbilateral inguinal lymphadenctomy done because there is crossing of lymphatics on both sides\nBartholin cyst produces a mass in the posterior part of the labium majus hydrocele of canal of nuck produces a mass in the anterior part of the labium majus\n\nNerve supply\nPudendal nerve supplies sensory fibres & motor fibres to the levator\nIlio-inguinal & genital branch of genito-femoral nerve give sensorry fibres\n\n',
    __v: 0,
  },
  {
    _id: '5e05a05b49cb620331b944d7',
    number: 9,
    content:
      'The uterus and vagina are held in the pelvis by the cardinal \nand utero-sacral ligaments- and by the pelvic floor musculature,\n mainly the levatores ani. \nWhen these ligaments and muscles become ineffective, the urerus and vagina descend (prolapse) through the gap between the muscles. \nThe Causes of Prolapse are:\n 1. The stretching of muscle and fibrous tissue which occurs with repeated.childbirth and damage to the innervation of the pelvic floor. \n2. Increased-intra-abdominal pressure (as in fat women with-chronic coughs) and in women who undertake heavy manual work. \n3. A constitutional predisposition to stretching of the ligaments as a response presumably to- years in the erect position. (Thus nulliparous women can develop prolapse: cf the constitutional factor in the development of varicose veins.) \nThe incidence of this condition in the United Kingdom is greatly reduced with improvement in obstetric techniques. The more liberal use of caesarean section and the elimination of long labours are probably the two most important factors. The uterus gradually descends in the axis of the vagina taking the vaginal wall with it. It may present clinically at any level, but is usually classifed as one of three degrees.\n First degreet cenvix still inside vagina.\n -- Second degree: the cervix-eppears Qutside the yulva. The cervicalips may become congested and ulcerated.\nthird degree: complete prolapse in the picture the uterus is retroflexed and the outline of bladder can be seen there may be a rectal prolapse as well this is sometimes called COMPLETE PROCIDENTIA',
    __v: 0,
  },
  {
    _id: '5e05a46949cb620331b944d8',
    number: 10,
    content:
      'VAGINAL PROLAPSE The prolapse is confined to the vaginal walls and the related viscera. The cervix may came down as well because of eiongation of the supravaginal cervix but-the uterus stays in the pelvis. Prulepse is C Cystocele Cystocele Anterior Prolapse When the upper part of the anterior wall prolapses, there is an underlying faihure of the investing fascia, and the bladder base niso descends. This is called a cystocele. Cysto cele Stretched urogenital Urethrocele Urethrocele wbeydejp Sometimes the tower part-of the vaginal wall prolapses and the urethra also descends. This is called a urethrocele and indicates-stretching of the urogenital diaphragm which holds the urethra to-the pubic bone.\n',
    __v: 0,
  },
  {
    _id: '5e05a4ef49cb620331b944d9',
    number: 11,
    content:
      " PROLAPSE OF THE POSTERIOR WALL often involved and rectu prolapses with vaginal wall. This is calied a rectocele, If the lowest part of the vagina prolapses, the perineal body is involved rather than the recrum. Enterocele If the upper part of the posterior vaginal wall prolapses, the Pouch of Douglas is elongated and small bowel or omennum may descend. This is called an enterocele. Enterocele is usually associated with uterine prolapse, as in the picture, and is sometimes called 'vanlk prolapse\" or \"hemia of the Pouch of Douglas'. The vaginal vault msy prolapse after hysterectomy. This is a dificult condition to treat One techniue suspends the vault from the sacro-liac ligaments using non-absorbable sutares. CLINICAL FEATURES OF THE PROLAPSE The common complaints are: 1. \"Something coming down' when the parient is on her feet. The sensation is not theze when she lies down. 2. Backache. This is often due simply to the patient being overweight. 3. Increased frequency.of micturition. This is at firt due to incomplete emptying, but sooner or later is aggravated by.cystitis. 4. A bearing down' sensation, analogous to the parturient woman's desire to push, This is probably.caused by pelvic venous congestign, and prespre from the abdominal contents on an inadequate pelvic floor. 5. Stress ncontinence. This is by no means always present. Sometimes it is found that reduction of the prolapse causes stress incontinence, 6- Coital problems. The patient may admit to difficultices with intercourse only on dircct questioning Difficulty in volding urine and defaecuting. The patient may find that it is impossible to initiate micturition except by pushing up the cystocele with her finger. In the same way the rectocele must be pushed back to allow emptying of the recturn. 7. The onset mnay be gradual or quite sudden and is commoner after the menopause when the genital traci tissues begin to atrophy.\n",
    __v: 0,
  },
  {
    _id: '5e05a55949cb620331b944da',
    number: 12,
    content:
      ' Urinary Incontinence Mechanism of continence: • The proximal part of the urethra is intrabdominal (above the levator ani): - When the intra-abdominal pressure is increased, it is transmitted equally to the bladder & proximal urethra producing a closure pressure in the proximal urethra which prevents passage of urine from the bladder to the urethra. - The pubo-urethral ligament & levator ani keep the proximal part of the urethra intra-abdominal. • The adult female urethra: Is about 4 cm in length and the surrounding intrinsic and extrinsic muscles provide a physiological sphincter. • The bladder contains B-receptors while the urethra contains a- adrenergic • receptors. The detrusor muscle should not contract during bladder filling. Stress Incontinence Definition: Involuntary loss of urine, through the urethra; when intra-abdominal pressure is increased & in absence of detrusor contractions. Causes 1. Congenital weakness of the ligaments & muscles supporting the bladder neck. 2. Obstetric weakness of the ligaments & muscles supporting the bladder neck. 3. Postmenopausal weakness due to atrophy of the ligaments. 4. Genital prolapse due to displacement of the bladder neck below the levator. NB: It is worsened by antihypertensives which block a-receptors in the urethra Diagnosis 1. History: Incontinence appears on stress as in straining or coughing. 2. Examination: The bladder should not be empty. a. Observation of incontinence: The patient is asked to cough & urethra is inspected - Hidden stress incontinence may be due to a large cystocele causing a kink of the urethra. To detect hidden stress incontinence, the prolapse\n\n\n\n',
    __v: 0,
  },
  {
    _id: '5e05a56349cb620331b944db',
    number: 13,
    content:
      'b. Bonney\'s teel The bladder neck is elevated by 2 fingers placed in the vagina taking care to place one finger on each side of the urethra so as ot to compER6 . *Il no urine escapes on coughing, the cause is bladder neck descent. -Ilurine escapen The cause le a weak bladder neck Qtip test: When the patient strains, the angle between the Q tip & the horizantal plane changes by greater than 30, it there is bladder neck descent. 3. Investigations: a. Urine analysle to exclude infection. b. Cystourethrometry r urodynamlca: This is done to differentiate detrusor instability te stress incontinuence. - In detrusor instability there is abrormal contractions during filling - In atresa incontinence there is decreased closure pressure which is the difference between the pressure in the urethra e bladder, c. Cystourethrography: - Loss of the posterior urethro-vesical angle in the lateral view. - Funneling in the anteroposterior view. Treatment: 1. Non-surgical treatment: *• Pontmenopausal atrophy: Hstrogen replacement therapy is glven. • Kegel exercines for 3-6 months, • Electrical stimulation of the pubococcygeun. 2. Surgical treatment: • Vaginal operatione - It is done for cases with prolapse. - Plication of the fascia around the bladder neck "Kelly\'s suture", • Colposuspension: An abdominal operation to suture the fascia around the bladder neck to, - The periosteum of the pubic bone "Marshall-Marchetti operation". - The pectineal part of the inguinal ligament "Burch operation". • Sling operationms in recurrent casen: A sling is pansed below the bladder neck &e is sutured to the rectus sheath; - The sling could be taken from the rectus sheath "Aldridge operation". -A nylon sling may be used "Pereyra operation",\n',
    __v: 0,
  },
  {
    _id: '5e05a5b249cb620331b944dc',
    number: 14,
    content:
      '14 Menopause Introduction AMertegse is permanent cessation of menses due to loss of the ovarian function. Clmacierie is the phase in the aging process of women during which there is transition from the reproductive stage of life to menopause. -The age of sporáneous menopause is 48-55 years (average 50 years). • Usually it is preceded by oligohypomenorrhea. • Sometimes it is abrupt & sudden. snodou snouqds jo yasO- SAndounu panAOG- - Induced "artificial" menopause: - Surgical due to bilateral oophorectomy. - Radiological ss a complication of radiotherapy for genital cancer. NE: The use of Gn Rh analogues more than 6 months leads to menopausal symptoms, however these symptoms are reversible. •Fremature mnenopause: - Menopause occurs before the age of 40 years. ABopon a. Constitutional. b. Hypergonadotropic hypogonadism e.g. Turner syndrome or radiotherapy - Diagnosis: Serum FSH > 40 m IU/ml. • Delayed menopause: - Menopause is delayed beyond the age of 55 years. - Eticlogy: a Constitutional. E. Estrogen producing ovarian tumors or uterine fibroids. - It is managed as a case of postmenopausal bleeding, due to liability to endometrial cancer. Changes after menopause 1. Hormonal changes: • Estrogens: - Estrogens decreases markedly & is unopposed i.e. no progesterone. - Estrone (E;) is the main estrogen after menopause due to pripheral conversion of androstenedione to estrone in the fat. Thus obese women are liable to endometrial hyperplasia & cancer.\n\n\n\n',
    __v: 0,
  },
  {
    _id: '5e05a5bc49cb620331b944dd',
    number: 15,
    content:
      "15 • Androgens: - Androstenedione is the main androgen after mUTKOpatuse. - IP's mainly produced by the suprarerial le also from the theca edis • Gonadotropins: - FSH: Increases above 40 mIU/ml due to absent feed-back ot estrogen - Few years later, levels of PSH & LH drop due to pituitary exhaustion. b. Postmenopausal osteoporosis: • Normally estrogen stimulates the osteoblasts k calcium absorptson from the GIT, • Estrogen deficiency leads to reduction of the boe density. C. Atherosclerosis & angina: Estrogen deficiency causes decreased HDL which is protective againet atherosclerosis, HDL carries cholesterol from the biood vessels to the liver. d. Genito-urinary & breast: • Atrophy of the vulva, vagina, cervix, body of the uterus & ovaries. • The vagina is liable to senile vaginitis because - The vagina becomes thin & atrophic. - The vaginal acidity is reduced. • Liability to senile endometritis due to absent endometrial shedding. • Atrophy of the ligaments causes genital prolapse & stress incontinence. • The breast shows atrophy. Clinical manifestation 1. Hot flushes: - Attacks of sensation of heat and sweating & sometimes followed by chills -Hot flushes are more at night and each attack lasts 1-4 minutes. - The attacks are due to vasodílatation followed by vasoconstriction. 2. Paychological disturbances: Depression, iritability or insomnda. 3. Sexual: Libido is usually diminished but sometimes increased or unchanged 4. Skeletal: Bone pains, fracture of the lower radius or the neck of femur. 5. Cardiovascular: Angina pectoris or myocardial infraction. 6. Senile vaginitis & endometritis. 7. Genital prolapse & stress incontinence.\n",
    __v: 0,
  },
  {
    _id: '5e05a6a649cb620331b944de',
    number: 16,
    content:
      'Management 1. Reassurance: Menopause is a change of life and not the end of life. 2. General treatment: - Avoidance of obesity & sedentary life i.e. exercise. - Calcium 1000 mg daily. 3. Hormone replacement therapy: a. Estrogen replacement therapy: • Aim: control hot flushes. - To prevent osteoporosis & angina. • Route: - Oral: Conjugated estorgen (Premarin), 0.625 mg/day. Its main problem is the hepatic first pass which causes its conjugation & decreased effec - Transdermal, either estrogen patch or gel. - Vaginal cream. It is specially used in cases of genital atrophy. • Contraindications to ERT are the same as contraceptive pills. b. Progestogen: To prevent endometrial cancer when given at least 14 days/cycle: - It decreases the endometrial estrogen receptors. - It has a direct antimitotic effect on the endometrial glands. NB: After hysterectomy estrogen is given alone to avoid side effects of progest c. Androgens: They have virilizing effect, thus better avoided.\n\n',
    __v: 0,
  },
  {
    _id: '5e05a6b049cb620331b944df',
    number: 17,
    content:
      '17 Gynecological Operations & procedures Hysterectomy Indications a. Obstetrical: 1. Irrepairable rupture of the uterus especially if the patient completed her family. 2. Couvelaire uterus if atonic & failed to contract with uterine massage & oxytocn. 3. Uncontrolled post-partum hemorrhage. 4. Placenta accreta. 5. Vesicular mole if the patient is above 40 years. b. Gynecological: 1. Benign neoplasms; - Fibroid, if the patient is above 40 years, large number of myomas that a useless behind uterus if myomectomy is done or if malignmancy is suspected. - Benign ovarian tumors if the patient is above 45 years. 2. Malignant neoplasms of the cervix, body and ovary. 3. Dysfunctional uterine bleeding in patients above 40 years with adequate number of children, if hormonal treatment & curettage failed to control bleeding. 4. 2nd or 3rd degree uterine prolapse in menopausal patients. 5. Endometriosis in patients above 40 years. 6. Genital tuberculosis if medical therapy fails in cases of large masses Types a. Abdominal hysterectomy: 1. Total hysterectomy: The body and cervix are removed. 2. Subtotal hysterectomy: The body is removed and the cervix is left.\n',
    __v: 0,
  },
  {
    _id: '5e05a71149cb620331b944e0',
    number: 18,
    content:
      '18 Gynecological Operations & procedures Advantages of total hysterectomy - Better drainage through the opened vagina, thut, lesS risk of peivic hematona. Advantages of subtotal hysterectomy - Easier and quicker - Injuries of the ureters & bladder are les. - Pelvic infection is less as the vagina is not opened - Avoids cervical stump carcinoma (1%) - The cervix act: as support for the vaginal vauit. - If the cervix infected, the Kource of the - The cervical mucus lubricates the vagina. infection is removed. Most gynecologists prefer total hysterectomy for the above reasons. Subtotal hysterectomy is usually for the following: - If rapid hysterectomy is needed e.g. uncontrollable post partum hemorrhage. - Extensive adhesions around the cervix. 3. Panhysterectomy: Total hysterectomy & bilateral salpingo-oophorectomy 4. Radical hysterectamy e.g. Wertheim operation. 5. Ultraradical hysterectomy "Pelvic excentration". b. Vaginal hysterectomy: • Indications: 1. Uterine prolapse (2nd or 3rd degree in menopausal patients) or chronic inversion. 2. Some cases of fibroids. 3. Schauta operation (see cancer cervix): the lymph nodes could not be removed 4. Some cases of dysfunctional uterine bleeding. • Advanteges of vaginal hysterectomy 1. Absence of an abdominal scar. 2 Less incidence of gastrointestinal complications and peritonitis. 3. Repair of an associated genital prolapse. • Disadvantages: 1. Unsafe and difficult in the presence of pelvic adhesions. 2 Could not be done if the uterus is > 12 weeks, unless bisected before removal. 3. The ovaries could not be removed in some cases. 4. The incidence of vault prolapse is more than after abdominal hysterectomy. Steps of total - Cutting & ligation of the round & the infudibulo- pelvic ligaments. - Downward mobilization of the bladder hysterectomy Steps of total vaginal hysterectomy - Circular incision around the cervix - Cutting & ligation of the uterine artery followed by the cardinal ligaments. Circular incision around the cervix - Upward mobilization of the bladder - Cutting & ligation of the cardinal ligaments followed by the uterine artery - Cutting & ligation of the round & the nfudibulo-pelvic ligaments.\n\n\n\n',
    __v: 0,
  },
  {
    _id: '5e05a71b49cb620331b944e1',
    number: 19,
    content:
      'Pelvic pain & dymenorrhea 61 Pelvic Pain 1. Cyclic pain i.e. dysmenorrhea or ovulation pain. 2 Acyclic pain: - Acute pain. -Chronic pain. Dysmenorrhea Dysmenorrhea is cyclic pain related to menstruation. Primary “Spasmodic" dysmenorrhea Etiology: The exact etiology is unknown, there are several theories, • Disturbed physiology: 1. Prostaglandins theory is the most accepted, evidenced by; - Pg Fza is released from the endometrium at the time of menses. This compound causes uterine contractions. - Prostaglandins are responsible for nausea & vomiting associated with dysmenorrhea as they lead to contractions of the gut ntuscles. - Prostaglandin synthesis occurs in ovulatory cycles only. - Antiprostaglandins relieve spasmodic dysmenorrhea. 2. Myometrial ischemia. 3. Disturbed polarity: The isthmus contracts instead of relaxing during menses. 4. Clotting of the menstrual blood ie. these clots are difficult to expel. • Disturbed anatomy. 1. Cervical stenosis so that the menstrual blood is difficult to expel. 2. Uterine anomalies e.g. Hypoplasia or cochleate uterus. • General factors: 1. Psychological factors: It is common in females, whose mothers suffer dysmenorrhea. 2. Low pain threshold. NB: It was found that blood endorphins level is low in females with low pain threshold & exercises increase its level. Endorphins decrease the pain.\n',
    __v: 0,
  },
  {
    _id: '5e05a79349cb620331b944e2',
    number: 20,
    content:
      'Peivic pain & dysinenarrhea Clinical picture: • It is common in virgirs or nulliparas and improves after childbirth. • It usually occurs 2-3 years after puberty i.e. with established ovulation. •Characters: It starts on the 1" day of menses & decreases gradually thereafter. - The pain is colicky, suprapubic & radiates to the inner aspects of the thighs along the ilio-inguinal nerve. - It is may be associated with nausea and sometimes vomiting. Treatment: 1. General measures: • Explanation and reassurance. • Physical exercises are advised & sedentary life is avoided. 2. Medical treatment: • Antiprostaglandins e.g. - Mefenamic acid "Ponstan" or brufens reduce prostaglandin synthesis & oppose its painful effect on the tissues, thus usually used. - Salicylates "Aspirin" reduces prostaglandin synthesis only. • Antispasmodics e.g. Hyoscine "Buscopan". • Calcium channel blockers eg. Nifedipine "Epilat". 3. Oral contraceptives: They lead to inhibition of ovulation and it is known that anovulatory cycles are usually not associated with spasmodic dysmenorrhea. 4. Surgical treatment: Surgery to treat 17 dysmenorrhea is very rarely if ever required. • Cervical dilatation: - It is done up to Hegar 14 to tear the paracervical sympathetic nerves. - Disadvantages: i, Pain may recur after 6-12 months due to regeneration of nerves. ii. Excess dilatation causes incompetent isthmus & recurrent abortion. • Presacral neurectomy: It is very rarely if ever done when all other methods fail. Membranous dysmenorrhea • It is considered as a rare type of spasmodic dysmenorrhea in which the endo- metrium separates as a big membranous cast. • Treatment: As spasmodic dysmenorrhea. Repeated curettage may be tried.\n\n\n\n',
    __v: 0,
  },
  {
    _id: '5e05a79c49cb620331b944e3',
    number: 21,
    content:
      'Pelvic pain & dysmenorrhea 21 Secondary "congestive" dysmenorrhea Etiology: Pelvic congestion due to; • Pelvic inflammations as chronic cervicitis & chronic salpingitis. • Neoplasms as uterine fibroids. Endometriosis & adenomyosis. • Genital prolapse and RVF. • Simple pelvic congestion e.g. coitus interruptus & constipation Clinical picture: • It is common in multiparous women • It occurs after years of relatively painless cycles. • Characters: - Pain starts 3-5 days premenstrual & is relieved by the onset of menses. - The pain is dull aching in the lower abdomen - It is associated with backache, menorrhagia & leucorrhea. • In endometriosis: - The pain starts 3-5 days before menstruation due to pelvic congestion. - It increases with menses, due to distension of the ectopic endometrium with blood. The pain decreases gradually after the end of menstruation due to absorption of blood. Treatment: 1. Treatment of the cause. 2.5% icthyol in glycerine vaginal pessaries: Glycerine is hygroscopic so it decreases the pelvic congestion and ichthyol is soothing. Ovarian dysmenorrhea •It is considered as a rare type of congestive dysnenorrhea in which ovarian congestion occurs especially if the turica albuginea is thick. • Premenstrual dull aching pain occurs in one or both iliac fossae. • Pain is reproduced by pressure on the ovaries during bimanual examination. • Treatment: - Analgesics. -5% icthyol in Glycerine vaginal pessaries. - In severe or resistant cases, ovarian sympathectomy is done by division & ligation of the infundibulopelvic ligament.\n',
    __v: 0,
  },
  {
    _id: '5e05a9c049cb620331b944e5',
    number: 22,
    content:
      'Pelvic pain & dysmenorrhea 22 Acyclic Chronic Pelvic Pain a. Gynecological causes: • Pelvic adhesions. • Inflammatory e.g. chronic salpingitis Neoplasms e.g. fibroids • Endometriosis. • Uterine prolapse. • Varicosities of the veins of the broad ligament. b. Non-gynecological causes: • Urinary e.g. cystitis or stones. • Rectal lesions e.g. anal fissure. • Musculo-skeletal pain. Low Backache a.Gynecological causes: • Pelvic adhesions. • Inflammatory e.g- chronic salpingitis • Neoplasms e.g- - Uterine fibroids. - Advanced pelvic cancer. • Endometriosis. • Uterine prolapse. • Varicosities of the veins of the broad ligament. b. Non-gynecological causes: • Rectal lesions e.g. anal fissure. • Musculo-skeletal pain. • Pregnancy due to exaggerated lordosis & relaxation of the ligaments. Backacke due to genital lesion shows the following: • It is sacral or lumbo-sacral. • It is diffuse: not indicated by the finger • Usually in the midline. • It is associated with local tenderness,\n\n\n\n',
    __v: 0,
  },
  {
    _id: '5e05a9d049cb620331b944e6',
    number: 23,
    content:
      "| 23 MATERNAL PHYSIOLOGIC CHANGES DURING PREGNANCY Genital changn Breast changer Skin changes Metabolic chanpes - Urinary changes raduous sojnatonojan)- - Respiratory changes Skeletal changet saducus puroopuz Pregnancy is a peculiar physiolopical state in which many changes take place; most of thesc charges are due to the effect of pregnancy hormones. Maternal physlological changes help adapta- bon of the woman's body to pregnancy, Understanding these changes is essential for: • Discriminating between normot pregnancy symptoms and those related to pathalogical condi- tions. • Understanding the effect of pregnancy on pre-existing diseases e.g, diabetes and heart diseases. • D'agnosis of pregnancy was prev.ously dependent.cn finding some of these charges, before the 1. GENITAL CHANGES np: sueaid 01eane pue kudesouor.n o ojunjona A) The Body of the Uterus: • The Height: The height Increases from 7.5 pm to reach 35 cm at term, due to: Oestrogen and progesterone leadinĘ tO TEyometrial hypertrophy and hyperplasia. The contents of the uterus i.e. foetus, placenta and amniotic fluld ..etc. • The Weight: The weight Inczeases from 50 gm to reach 1000 Bm at term. The Shape: The shape of the uterus is globular (till 14 weeks then it becomes pyriform. The uterine ligaments: Show hypertrophy. Dextro-rotation: The uterus is tiited and twisted to the right in 80% of cases. Braxton-Hicks contractions: irregular, painless con- tractions that help placental circulation. The Lower Uterine Segment (LUS): The LUS is formed from the Isthmus Ut starts to be formed from the Ath month to reach 10 crr. at full term, Obstetric signincance of the LUS: a, anatomical Internal os E histological internal os 2. former isthmus d. cervix 1.Site of lower sERment cesarean sectlen (LSCS) 3.5tecfimplantaton Incases of placenta previa. Fig -1 Farmetion of the LUS\n",
    __v: 0,
  },
  {_id: '5e05b0c649cb620331b944e9', number: 24, content: 'dd  ', __v: 0},
  {
    _id: '5e05b0b249cb620331b944e7',
    number: 25,
    content:
      '25 4. METABOLIC CHANGES A. Protein metabolism: (arabolic state) B. Carbohydrates metabolism: (ciabetogenic state) Progressive increase in Insulin requirements due to insulin antagonism and resistance by: A Placental hormones; human placental iactogen (HPL), oestrogen (E), arıd progesterone (P). 2. Production of insulinase enzyme by the placenta • Alimentary glycosuria due to rapid absorption of glucose from the GIT. • Renal glycosuria due to lowering of the renal threshold (increase loss of glucose in urine). • Lowered fasting blood glucose due to transfer of giucose to the foetus (fasting hypoglycaemia). C. Fat metabolism: Increased lipolysis to deliver more free fatty aids to the foetus D. Minerals: Increased requirements of iron, calclum, phosphorus and iodides. E. Water: Salt and water retention.occurs due to the effect of oestrogen and progesterone. F. Weight: The average total weight gain is 9-14 kg most of it occurs In the 3rd trimester. 5. URINARY CHANGES A Dilatation of the ureters: due to: • Atony of the ureteric muscles caused by progesterong and relaxip. • Hypertrophy of the lower end of the ureter caused by oestrogen together with pressure of the uterus on the ureter. This effect is more on the right ureter due to dextro-rotation of the uter- "sn . Ureteric atony and pressure of gravid uterus lead to stosis of urine that predispose td urinary tract infection (UTIJ. B. Frequency of micturition: due to pressure.of.the pregnant uterus on the urinary bladder in the 1st trimester and again with engagement of the head late in pregnancy in last few weeks. 6. GASTRO-INTESTINAL CHANGES •Emesis gravidarum morning siekness", and sometimes with increased salivation (ptyalism). • Heart burn "reflux esaphagitis" caused by relaxation of the cardiac sphincter due to the effect of progesterone and relaxin . Decreased gastric acidity (HCI) which, may interfere with iron absorption, teading to anaemla. . Constipation due to reduced gut motility caused by progesterone. • Relaxation of the gall bladder with a tendency to stone formation. 7. CARDIOVASCULAR CHANGES A. The Blood Volume: . Total blood volume increases aimost40f by the end of 32 week.of pregnancy. . Plasma volume increases by 45%leRECa increase only 154 leading to hemodilution. Hemodilution.causes physialogical anaemin and hyperdynamic circulation (functional mur- murs).\n\n\n\n',
    __v: 0,
  },
  {
    _id: '5e05b0ba49cb620331b944e8',
    number: 26,
    content:
      'Meternal Physiologic Chonpes During Pregnancy • The CO increase soa peak at the 32 weakot prepnancy (about 40% increase) which remains elevated the and of pregnancy. Increasen CO is due to an both increasec stroke velume (the Tmain zeason) andincreased in the heartsate (15%) towards the end.af pregnancy. C.The blood pressure (BP): • A normal BP in Ęemeral has a mean of 120/80. During pregnancy a slight drop in the BP occurs In the 2 trimester due to opening of arterio-venous shunts at the placenta. B. The Cardiac Output (CO): • Hypertension (HTN) is diagnosed in pregnancy when the BP is 140/90 or more, on two.acca- sions, 6 hours Or more apart. • Supine hypotension syndrome:In the 2 half of pregnancy, maternal hypotersion occurs in the supine position due to pressure of the pregrnant uterus on the inferior vena-cava. This leads to decreased venous return and cardiac output. D. Cardiac changes: 1. Displacement of the apex of heart in late pregnancy, to-the 4 intercostal space, due to eleva- tion ot the diaphregmand the heart by the fundus of the growing uterus. 2. Functional murmurs are detected and are usually systolic. E. Venous stasis: Pressure of the uterus on the pelvic veins leads to ankle oedema, varicose veins and piles. F. Blood changes: Increased fibrinogen (up to 600 mg%) and WBCS (leucocytosis up to 12,000/mm). 8. RESPIRATORY CHANGES • Hyperventilation accurs, es progesterone stimulates the respiratory centre. • Limitation of movement of the diaphragm in late pregnancy causes dyspnoea. 9. SKELETAL CHANGES Increased lumbar lordosis may cause low back pain. Relaxation of pelvic joints and ligaments due to progesterone and relaxin may cause pelvic sued 10. ENDOCRINAL CHANGES • The Pituitory-gland: The anterior pitultary-increases-in size-and-activity, while the posterior pituitary releases oxytocin at the.onset of labour. - The Thyrold gland: increases in size.and activity (physlalogical.goitre). Total T4 is increased but the free T4 is within normal levels. - The Parathyroid gland; Increases in size and activity to regulate calcium.metabolism, . The Adrenal gland; increases in size.and activity. Cortisol is increased but the main Increase is in the bound.portion.\n',
    __v: 0,
  },
  {_id: '5e05775a49c30c1795effbe7', number: 47, content: 'test', __v: 0},
  {_id: '5e0577794248da17a6224b37', number: 48, content: 'asd', __v: 0},
];
export default pages;
